# Generated by Django 3.0.5 on 2020-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetailpage',
            name='external_link_two',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexdetailpage',
            name='sourceforabouttext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source for about text'),
        ),
        migrations.AlterField(
            model_name='indexdetailpage',
            name='author_founder',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Author/Founder'),
        ),
        migrations.AlterField(
            model_name='indexdetailpage',
            name='contributed_by',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contributed By'),
        ),
    ]
