# Generated by Django 3.0.5 on 2020-06-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200613_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdetailpage',
            name='custom_title',
        ),
    ]
