# Generated by Django 3.0.5 on 2020-06-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_indexdetailpage_custom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdetailpage',
            name='range_date',
        ),
        migrations.AddField(
            model_name='indexdetailpage',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
