# Generated by Django 3.0.5 on 2020-06-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200614_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesorderable',
            name='custom_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Alt'),
        ),
    ]
