# Generated by Django 3.0.5 on 2020-06-17 01:04

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_imagesorderable_custom_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdetailpage',
            name='about',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
