# Generated by Django 3.0.5 on 2020-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200617_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetailpage',
            name='rownum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
