# Generated by Django 3.0.5 on 2020-08-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_indexdetailpage_rownum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexdetailpage',
            options={'verbose_name': 'Index Detail Page', 'verbose_name_plural': 'Index Detail Pages'},
        ),
    ]
