# Generated by Django 3.0.5 on 2020-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_indexdownloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdownloads',
            name='date',
        ),
        migrations.RemoveField(
            model_name='indexdownloads',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='indexdownloads',
            name='time',
        ),
        migrations.AddField(
            model_name='indexdownloads',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
