# Generated by Django 3.0.5 on 2020-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200815_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdownloads',
            name='name',
        ),
        migrations.AddField(
            model_name='indexdownloads',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
