# Generated by Django 3.0.5 on 2020-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200815_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdownloads',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='indexdownloads',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='time'),
        ),
    ]
