# Generated by Django 3.0.5 on 2020-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200815_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdownloads',
            name='date',
        ),
        migrations.RemoveField(
            model_name='indexdownloads',
            name='time',
        ),
        migrations.AddField(
            model_name='indexdownloads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
