# Generated by Django 3.0.5 on 2022-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20200815_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesorderable',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='caption'),
        ),
    ]
